### ISSUE TITLE
After forking mainnet, 'invalid signer' error

### ISSUE THREAD

**Issue by sdavidkong** [PatrickAlphaC/hardhat-defi-fcc#16]
Hello, 

I've just gotten to the part of the course where we are forking mainnet and it appears that it won't accept any of the fake hardhat accounts to call the getWeth() function. The output is as follows:

  reason: 'invalid signer',
  code: 'INVALID_ARGUMENT',
  argument: 'signer',
  value: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
}
error Command failed with exit code 1.

Any help would be appreciated!

**Comment by sdavidkong** [comment]
Sorry nevermind, figured it out. It was an issue with ethers.js. Because I started with the Chainlink hardhat starter kit, my package.json is different than the one for this repo. I copied over package.json and reinstalled the dependencies and it worked just fine. Frustrating.

**Comment by bai1507** [comment]
"@nomiclabs/hardhat-ethers" this package go wrong!!!OMG,it take me a long time to solve this!

**Comment by PatrickAlphaC** [comment]
@bai1507 what happened?

**Comment by Wonder0xWeird** [comment]
For anyone still struggling with this, remember to set your hardhat-ethers package to run on hardhat-deploy-ethers

terminal:
```
yarn add --dev hardhat-deploy-ethers
```

package.json
```
"@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers",
```
