### ISSUE TITLE
aaveBorrow failing with Goerli network (working perfectly fine locally)

### ISSUE THREAD

**Issue by etienneadaher** [PatrickAlphaC/hardhat-defi-fcc#20]
```await lendingPool.deposit(wethTokenAddress, AMOUNT, deployer, 0)```

Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":3...
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: ProviderError: execution reverted: 2
  
  - Verified addresses (weth, lending protocols, feeds ... )
  - Increased gas limit with hardhat setup: allowUnlimitedContractSize, blockGasLimit...

Nothing helped, still failing. Any help would be appreciated. Thank you.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

**Comment by etienneadaher** [comment]
Done: https://github.com/smartcontractkit/full-blockchain-solidity-course-js/issues/4872
