### ISSUE TITLE
Error: failed to get chainId, falling back on net_version... ConnectTimeoutError: Connect Timeout Error

### ISSUE THREAD

**Issue by PhilRandWu** [PatrickAlphaC/hardhat-defi-fcc#26]
// hardhat.config.ts

```ts
hardhat: {
            chainId: 31337,
            forking: {
                url: MAINNET_RPC_URL,
                blockNumber: 14390000
            },
        },
```
MAINNET_RPC_URL  =  https://mainnet.infura.io/v3/key 

// network.config.ts
```ts
  31337: {
        name: "localhost",
        wethToken: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
        lendingPoolAddressesProvider: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5",
        daiEthPriceFeed: "0x773616E4d11A78F511299002da57A0a94577F1f4",
        daiToken: "0x6b175474e89094c44da98b954eedeac495271d0f",
    },
```
It's just a call to the getWeth function，then Error: failed to get chainId, falling back on net_version... ConnectTimeoutError: Connect Timeout Error

**Comment by PatrickAlphaC** [comment]
Thanks for this!

Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/

**Comment by PhilRandWu** [comment]
Ok, no problem, thanks for the reply
