### ISSUE TITLE
Error: could not decode result data (value="0x", info={ "method": "getLendingPool", "signature": "getLendingPool()" }, code=BAD_DATA, version=6.9.0)

### ISSUE THREAD

**Issue by UnknownBlackman** [PatrickAlphaC/hardhat-defi-fcc#27]
Hello Patrick and other smart contract developers. I'm getting an error "Could not decode result" when trying to get lending pool address from the lendingPoolAddressesProvider. I have my getLendingPool function below

```
async function getLendingPool(account) {
    /**LendingPoolAddresses Provider address
     * Goerli=0x5E52dEc931FFb32f609681B8438A51c675cc232d
     * Mainnet= 0x5E52dEc931FFb32f609681B8438A51c675cc232d
     */

    const lendingPoolAddressesProvider = await ethers.getContractAt(
        "ILendingPoolAddressesProvider",
        "0x5E52dEc931FFb32f609681B8438A51c675cc232d",
        account
    )

    /**There's an error here that I can't solve. Would come back to it
     * Update: Is it possible that lendingPoolAddressesProvider no longer returns
     * ...lendingPool address since its outdated and no longer in use?
     */
    const lendingPoolAddress =
        await lendingPoolAddressesProvider.getLendingPool()

    console.log(lendingPoolAddress)

    const lendingPool = await ethers.getContractAt(
        "ILendingPool",
        lendingPoolAddress,
        account
    )

    return lendingPool
}
```

I'm using ethers v6.9.0 but my first instinct is that getLendingPool no longer returns an address due to aave V2 being no longer in use. I may be wrong. Please I need feedbacks so I can continue with the lesson.

**Comment by PatrickAlphaC** [comment]
Hmmm are you using the correct chain? The correct address based on the docs?

**Comment by UnknownBlackman** [comment]
> Hmmm are you using the correct chain? The correct address based on the docs?

This is embarrassing but I was actually passing in goerli lendingPoolAddressesProvider address instead of the mainnet address. It's fine now so I would just close this. Welp
